language: node_js

sudo: false

node_js:
  - "5.7"
  - "4.3"
  - "0.12"
  - "0.10"

cache:
  directories:
    - node_modules

before_install:
  - npm install -g npm@latest

script:
  - gulp lint
  - gulp test:mocha
  - npm run codecov
